### ISSUE TITLE
Add highlighting to operators

### ISSUE THREAD

**Issue by aloussase** [yorickpeterse/nvim-grey#1]
Hi! I really love this theme, I've been using it since it got recommended to me on reddit after I made a post about having sensitive eyes. One issue I have with it is that there is no highlighting for operators, which makes it a bit difficult to see at first glance what is going on. Would you consider adding some highlighting for operators? It can be something subtle, just a visual cue that it is a special character.

**Comment by yorickpeterse** [comment]
@aloussase I'm not a fan of applying highlights to the `Operator` group, mostly because every language uses this group differently. Some only apply it to actual operators (e.g. `+` or `/`), while others also use it for more generic symbols such as `(`, `;`, etc. The result is that if you apply a highlight to this group, things can quickly become too noisy.

What you could do is set up an `autocmd` for the `ColorScheme` group, i.e. something like `autocmd ColorScheme grey hi Operator gui=bold`. This way you can apply custom changes to the theme, without it affecting other themes or requiring changes to the source code.
